package com.p2p.common.protocol;

/** Commands exchanged over the control TCP connection. */
public enum MessageType {
    JOIN_REQUEST, JOIN_RESPONSE,
    USER_LIST_REQUEST, USER_LIST_RESPONSE, USER_STATUS_CHANGED,
    PRIVATE_MESSAGE, GROUP_MESSAGE,
    CREATE_ROOM, JOIN_ROOM, LEAVE_ROOM, ROOM_UPDATED,
    FILE_OFFER, FILE_ACCEPT, FILE_REJECT, FILE_CANCEL,
    FILE_CHUNK, FILE_PROGRESS, FILE_COMPLETE, FILE_FAILED,
    FILE_SEARCH_REQUEST, FILE_SEARCH_RESPONSE, FILE_SHARE, FILE_UNSHARE,
    PING, PONG, ERROR
}
